apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-service
  namespace: parkit
spec:
  replicas: 12
  selector:
    matchLabels:
      app: analysis-service
  template:
    metadata:
      labels:
        app: analysis-service
    spec:
      containers:
      - name: analysis-service
        image: parkitteam/analysis-service:latest
        ports:
        - containerPort: 8080
