apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-service
  namespace: parkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis-service
  template:
    metadata:
      labels:
        app: analysis-service
    spec:
      containers:
      - name: analysis-service
        image: parkitteam/analysis-service:build-62
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        env:
        - name: SERVER_PORT
          value: "8081"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "my-kafka:9092"
        - name: SPRING_DATA_REDIS_HOST
          value: "redis"
