apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: parkit
data:
  grafana.ini: |
    [server]
    root_url = http://192.168.201.98:50030/grafana/
    serve_from_sub_path = true
    [security]
    admin_user = admin
    admin_password = admin