apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-service        
  namespace: parkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-service     
  template:
    metadata:
      labels:
        app: socket-service   
    spec:
      containers:
      - name: socket-service  
        image: parkitteam/socket-service:build-36
        ports:
        - containerPort: 8082 
        env:
        - name: SERVER_PORT
          value: "8082"
        - name: SPRINGDOC_SWAGGER_UI_CONFIG_URL
          value: "/socket/v3/api-docs/swagger-config"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "my-kafka:9092"
