apiVersion: v1
kind: Service
metadata:
  name: socket-service        # 변경
  namespace: parkit
spec:
  selector:
    app: socket-service       # 변경
  ports:
  - port: 8080
    targetPort: 8080          # socket-service 실제 포트로 변경
  type: ClusterIP
