apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: parkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: parkitteam/report-service:build-81
        ports:
        - containerPort: 8083
        env:
        - name: SERVER_PORT
          value: "8083"
        - name: SPRINGDOC_SWAGGER_UI_CONFIG_URL
          value: "/report/v3/api-docs/swagger-config"
        - name: SPRINGDOC_SWAGGER_UI_URL
          value: "/report/v3/api-docs"
        - name: SPRINGDOC_SWAGGER_UI_DISABLE_SWAGGER_DEFAULT_URL
          value: "true"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "my-kafka:9092"

        - name: SPRING_MONGODB_URI
          value: "mongodb://mongodb:27017/parkit"

        - name: SPRING_REDIS_HOST
          value: "redis"

        - name: SPRING_REDIS_PORT
          value: "6379"
