apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: parkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: parkitteam/report-service:build-16
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "my-kafka:9092"
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://mongodb:27017/parkit"
