apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: parkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
      - name: report-service
        image: parkitteam/report-service:build-9
        ports:
        - containerPort: 8080
