apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
  namespace: parkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
      - name: client-service
        image: parkitteam/client-service:build-42
        ports:
        - containerPort: 80
