apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/your-repo/argocd-parkit.git
    targetRevision: HEAD
    path: redis

  destination:
    server: https://kubernetes.default.svc
    namespace: parkit

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
